 export const RESPONSE_DATA = {
  products: [
    {
      _id: "6a4612943ce84c7148360bac",
      productName: "Kundan Bridal Choker Set",
      slug: "kundan-bridal-choker-set",
      productDescription:
        "Heavy kundan and pearl choker set with matching earrings, designed for weddings.",
      price: 8500,
      discountPrice: 6999,
      category: "necklaces",
      stockQuantity: 5,
      rating: 0,
      numReviews: 0,
      productImageUrl: [
        "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTFXxIx1YeJVZBsLYPNt4a7sJsmaOFf39CrF2KDvoGqunnoAaLFiQmF6uQUQuFtMAsaCvLHBb8T6-Ag36ziZcf8D3Pni8Yqw0QAITLZ4RkS8U-27cL335B7",
      ],
      tags: ["kundan", "bridal", "choker", "wedding"],
      status: "active",
      isFeatured: true,
      createdAt: "2026-07-02T07:26:12.912Z",
    },
    {
      _id: "6a4612863ce84c7148360bab",
      productName: "Rose Gold Solitaire Ring",
      slug: "rose-gold-solitaire-ring",
      productDescription:
        "Elegant rose gold-plated ring with cubic zirconia solitaire.",
      price: 899,
      discountPrice: null,
      category: "rings",
      stockQuantity: 40,
      rating: 1,
      numReviews: 0,
      productImageUrl: [
        "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTFXxIx1YeJVZBsLYPNt4a7sJsmaOFf39CrF2KDvoGqunnoAaLFiQmF6uQUQuFtMAsaCvLHBb8T6-Ag36ziZcf8D3Pni8Yqw0QAITLZ4RkS8U-27cL335B7",
      ],
      tags: ["rose gold", "ring", "solitaire"],
      status: "active",
      isFeatured: false,
      createdAt: "2026-07-02T07:25:58.384Z",
    },
    {
      _id: "6a4612723ce84c7148360baa",
      productName: "Silver Oxidized Jhumka Earrings",
      slug: "silver-oxidized-jhumka-earrings",
      productDescription:
        "Traditional oxidized silver jhumkas with temple-style carving, handcrafted finish.",
      price: 1200,
      discountPrice: 999,
      category: "earrings",
      stockQuantity: 25,
      rating: 0,
      numReviews: 0,
      productImageUrl: [
        "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTFXxIx1YeJVZBsLYPNt4a7sJsmaOFf39CrF2KDvoGqunnoAaLFiQmF6uQUQuFtMAsaCvLHBb8T6-Ag36ziZcf8D3Pni8Yqw0QAITLZ4RkS8U-27cL335B7",
        "https://example.com/images/jhumka-side.jpg",
      ],
      tags: ["silver", "oxidized", "earrings", "traditional"],
      status: "active",
      isFeatured: true,
      createdAt: "2026-07-02T07:25:38.499Z",
    },
    {
      _id: "6a44d1edf5c1bf738482e7f4",
      productName: "Gold Heart Necklace",
      slug: "gold-heart-necklace",
      productDescription: "18K gold plated heart necklace with premium finish.",
      price: 4999,
      discountPrice: 3999,
      category: "necklaces",
      stockQuantity: 25,
      rating: 0,
      numReviews: 0,
      productImageUrl: [
        "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTFXxIx1YeJVZBsLYPNt4a7sJsmaOFf39CrF2KDvoGqunnoAaLFiQmF6uQUQuFtMAsaCvLHBb8T6-Ag36ziZcf8D3Pni8Yqw0QAITLZ4RkS8U-27cL335B7",
        "https://example.com/images/necklace-back.jpg",
      ],
      tags: ["gold", "heart", "women", "jewellery"],
      status: "active",
      isFeatured: true,
      createdAt: "2026-07-01T08:38:05.671Z",
    },
  ],
  pagination: {
    total: 4,
    page: 1,
    limit: 12,
    totalPages: 1,
    hasNextPage: false,
    hasPrevPage: false,
  },
};